CREATE DATABASE octank;

CREATE TABLE Purchases (
  OrderId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Store VARCHAR(255) NOT NULL,
  Product VARCHAR(255) NOT NULL,
  DateTime DATETIME NOT NULL,
  Cost INT NOT NULL
);